better vignette index in pkgdown?
ropensci/vcr pull request #202
Opened 2020-11-26 10:30 UTC by maelle

* All vignette titles now start with a capital letter and are a sentence
* Add an order from easy/most basic usage to advanced.

2020-11-30 18:32 UTC, sckott commented on vignettes/configuration.Rmd
> +title: "Tweak vcr default configuration"
Could we use a different word than tweak? would "manage vcr configuration" be better?

2020-11-30 18:34 UTC, sckott commented on vignettes/request_matching.Rmd
> +title: "Tweak vcr request matching"
similar comment, could we maybe not use tweak

2020-11-30 18:34 UTC, sckott requested changes
In the vignette title "Why and how edit your vcr cassettes?" could we change to "Why and how __to__ edit your vcr cassettes?"

2020-12-01 08:16 UTC, maelle commented
I made changes. Now I wonder whether it'd be clearer if request matching were merged into "configure vcr" as it's part of configuration?

2020-12-01 16:02 UTC, sckott commented
No, I think request matching just deserves more attention than most other configuration settings - we should at some point fill out that matching vignette more

2020-12-01 16:03 UTC, sckott approved these changes

2020-12-01 16:03 UTC, merged